version: '3.8'

services:

  db:
    image: mariadb:10.6.2
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MARIADB_DATABASE: ${WORDPRESS_DB_NAME:-wordpress}
      MARIADB_USER: ${WORDPRESS_DB_USER:-wordpress}
      MARIADB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-password}
    volumes:
      - ./mariadb/db-data:/var/lib/mysql
      - ./mariadb/db-conf:/etc/mysql/conf.d
      - ./mariadb/db-init:/docker-entrypoint-initdb.d
    networks:
      - wordpress-network

  wordpress:
    image: wordpress:php7.4-fpm-custom
    build: ./wordpress
    container_name: wordpress
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-wordpress}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-password}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-wordpress}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX:-wp_}
    volumes:
      - ./wordpress/php.ini-production:/usr/local/etc/php/php.ini
      - ./${DOMAIN_NAME:-web_root}:/var/www/html
    restart: always  
    networks:
      - wordpress-network

  nginx:
    image: nginx:1.21.0.custom
    build: ./nginx
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    restart: always
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./tools/certbot/certs/live/${DOMAIN_NAME}:/etc/nginx/certs
      - ./${DOMAIN_NAME:-web_root}:/var/www/html
    networks:
      - wordpress-network
  

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=db
      - PMA_ABSOLUTE_URI=/phpmyadmin/
    networks:
      - wordpress-network

networks:
  wordpress-network:
    driver: bridge